### ISSUE TITLE
g2o related problems

### ISSUE THREAD

**Issue by cuicuihaohaoxuexi** [ningwang1028/lidar_slam_3d#3]
I have used the lidar_slam_3d pkg and when I run 'catkin_make', it has link problem related to g2o. I am using ubuntu 14.04 and ros indigo. Neither the indigo libg2o or the latest g2o works for your pkg. May you tell me what is the suitable version of g2o for this pkg? Thanks!

**Comment by ningwang1028** [comment]
commit id ff647bd7537860a2b53b3b774ea821a3170feb13
Try this version.

**Comment by cuicuihaohaoxuexi** [comment]
Thanks for your fast response! After I change g2o version to the one you provide, everything builds fine and your package works. Thanks a lot for your help!
